// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4xcx0pVKKAf9IjIvu7d8a2s6x6zodSs',
    appId: '1:490466120061:web:426bb7eaf4d38d958ebc14',
    messagingSenderId: '490466120061',
    projectId: 'easyknowledge-6a1a3',
    authDomain: 'easyknowledge-6a1a3.firebaseapp.com',
    storageBucket: 'easyknowledge-6a1a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXd5N_aTgVBqs24h_chkzNNsX3o4GjIs',
    appId: '1:490466120061:android:95ab5fcf7bbbcad28ebc14',
    messagingSenderId: '490466120061',
    projectId: 'easyknowledge-6a1a3',
    storageBucket: 'easyknowledge-6a1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oB6DB8kLQJx9mgprElmTJwY3LfOwSrU',
    appId: '1:490466120061:ios:8e25668ec3e9d3eb8ebc14',
    messagingSenderId: '490466120061',
    projectId: 'easyknowledge-6a1a3',
    storageBucket: 'easyknowledge-6a1a3.firebasestorage.app',
    iosBundleId: 'com.example.easyKnowledge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5oB6DB8kLQJx9mgprElmTJwY3LfOwSrU',
    appId: '1:490466120061:ios:8e25668ec3e9d3eb8ebc14',
    messagingSenderId: '490466120061',
    projectId: 'easyknowledge-6a1a3',
    storageBucket: 'easyknowledge-6a1a3.firebasestorage.app',
    iosBundleId: 'com.example.easyKnowledge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf4xcx0pVKKAf9IjIvu7d8a2s6x6zodSs',
    appId: '1:490466120061:web:e401ec1e41715ba38ebc14',
    messagingSenderId: '490466120061',
    projectId: 'easyknowledge-6a1a3',
    authDomain: 'easyknowledge-6a1a3.firebaseapp.com',
    storageBucket: 'easyknowledge-6a1a3.firebasestorage.app',
  );
}
